---
version: "2"
linters:
  default: all
  disable:
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - gocritic
    - lll
    - nestif
    - noctx
    - nonamedreturns
    - perfsprint
    - testifylint
    - testpackage
    - varnamelen
    - wrapcheck
  settings:
    depguard:
      rules:
        main:
          files:
            - "!**/*_a _file.go"
          allow:
            - $gostd
            - github.com/aws/aws-lambda-go/lambda
            - github.com/aws/aws-sdk-go-v2/aws
            - github.com/aws/aws-sdk-go-v2/config
            - github.com/aws/aws-sdk-go-v2/credentials/stscreds
            - github.com/aws/aws-sdk-go-v2/feature/s3/manager
            - github.com/aws/aws-sdk-go-v2/service/ecr
          deny:
            - pkg: log
              desc: Use "log "github.com/sirupsen/logrus"" instead
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: internal/pkg/data/trivy_types.go
        text: "exported: type name will be used as data.DataSource"
      - linters:
          - funlen
        path: internal/app/mcvs-scanner/data/data_integration_test.go
        text: Function "TestInsertImageSBOMIntoDB" is too long
    paths:
      - internal/app/mcvs-scanner-cli/application/swagger
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: disable
    paths:
      - internal/app/mcvs-scanner-cli/application/swagger
      - third_party$
      - builtin$
      - examples$
