// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewStorer creates a new instance of Storer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storer {
	mock := &Storer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Storer is an autogenerated mock type for the Storer type
type Storer struct {
	mock.Mock
}

type Storer_Expecter struct {
	mock *mock.Mock
}

func (_m *Storer) EXPECT() *Storer_Expecter {
	return &Storer_Expecter{mock: &_m.Mock}
}

// DownloadFileFromURL provides a mock function for the type Storer
func (_mock *Storer) DownloadFileFromURL(url string) ([]byte, error) {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFileFromURL")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(url)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storer_DownloadFileFromURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFileFromURL'
type Storer_DownloadFileFromURL_Call struct {
	*mock.Call
}

// DownloadFileFromURL is a helper method to define mock.On call
//   - url string
func (_e *Storer_Expecter) DownloadFileFromURL(url interface{}) *Storer_DownloadFileFromURL_Call {
	return &Storer_DownloadFileFromURL_Call{Call: _e.mock.On("DownloadFileFromURL", url)}
}

func (_c *Storer_DownloadFileFromURL_Call) Run(run func(url string)) *Storer_DownloadFileFromURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Storer_DownloadFileFromURL_Call) Return(bytes []byte, err error) *Storer_DownloadFileFromURL_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Storer_DownloadFileFromURL_Call) RunAndReturn(run func(url string) ([]byte, error)) *Storer_DownloadFileFromURL_Call {
	_c.Call.Return(run)
	return _c
}

// WriteTextFile provides a mock function for the type Storer
func (_mock *Storer) WriteTextFile(dest string, content string) error {
	ret := _mock.Called(dest, content)

	if len(ret) == 0 {
		panic("no return value specified for WriteTextFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(dest, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storer_WriteTextFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteTextFile'
type Storer_WriteTextFile_Call struct {
	*mock.Call
}

// WriteTextFile is a helper method to define mock.On call
//   - dest string
//   - content string
func (_e *Storer_Expecter) WriteTextFile(dest interface{}, content interface{}) *Storer_WriteTextFile_Call {
	return &Storer_WriteTextFile_Call{Call: _e.mock.On("WriteTextFile", dest, content)}
}

func (_c *Storer_WriteTextFile_Call) Run(run func(dest string, content string)) *Storer_WriteTextFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storer_WriteTextFile_Call) Return(err error) *Storer_WriteTextFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Storer_WriteTextFile_Call) RunAndReturn(run func(dest string, content string) error) *Storer_WriteTextFile_Call {
	_c.Call.Return(run)
	return _c
}

// WriteToFile provides a mock function for the type Storer
func (_mock *Storer) WriteToFile(dest string, data []byte) error {
	ret := _mock.Called(dest, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteToFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(dest, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storer_WriteToFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteToFile'
type Storer_WriteToFile_Call struct {
	*mock.Call
}

// WriteToFile is a helper method to define mock.On call
//   - dest string
//   - data []byte
func (_e *Storer_Expecter) WriteToFile(dest interface{}, data interface{}) *Storer_WriteToFile_Call {
	return &Storer_WriteToFile_Call{Call: _e.mock.On("WriteToFile", dest, data)}
}

func (_c *Storer_WriteToFile_Call) Run(run func(dest string, data []byte)) *Storer_WriteToFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storer_WriteToFile_Call) Return(err error) *Storer_WriteToFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Storer_WriteToFile_Call) RunAndReturn(run func(dest string, data []byte) error) *Storer_WriteToFile_Call {
	_c.Call.Return(run)
	return _c
}
