// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"log/slog"

	"github.com/schubergphilis/mcvs-golang-action/internal/app/mcvs_golang_action_bootstrap/application"
	mock "github.com/stretchr/testify/mock"
)

// NewExecutor creates a new instance of Executor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Executor {
	mock := &Executor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Executor is an autogenerated mock type for the Executor type
type Executor struct {
	mock.Mock
}

type Executor_Expecter struct {
	mock *mock.Mock
}

func (_m *Executor) EXPECT() *Executor_Expecter {
	return &Executor_Expecter{mock: &_m.Mock}
}

// DownloadFiles provides a mock function for the type Executor
func (_mock *Executor) DownloadFiles(jobs []application.DownloadJob) error {
	ret := _mock.Called(jobs)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFiles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]application.DownloadJob) error); ok {
		r0 = returnFunc(jobs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Executor_DownloadFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFiles'
type Executor_DownloadFiles_Call struct {
	*mock.Call
}

// DownloadFiles is a helper method to define mock.On call
//   - jobs []application.DownloadJob
func (_e *Executor_Expecter) DownloadFiles(jobs interface{}) *Executor_DownloadFiles_Call {
	return &Executor_DownloadFiles_Call{Call: _e.mock.On("DownloadFiles", jobs)}
}

func (_c *Executor_DownloadFiles_Call) Run(run func(jobs []application.DownloadJob)) *Executor_DownloadFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []application.DownloadJob
		if args[0] != nil {
			arg0 = args[0].([]application.DownloadJob)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Executor_DownloadFiles_Call) Return(err error) *Executor_DownloadFiles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Executor_DownloadFiles_Call) RunAndReturn(run func(jobs []application.DownloadJob) error) *Executor_DownloadFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateMockeryYaml provides a mock function for the type Executor
func (_mock *Executor) GenerateMockeryYaml(moduleName string, dir string, outPath string, logger *slog.Logger) error {
	ret := _mock.Called(moduleName, dir, outPath, logger)

	if len(ret) == 0 {
		panic("no return value specified for GenerateMockeryYaml")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, *slog.Logger) error); ok {
		r0 = returnFunc(moduleName, dir, outPath, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Executor_GenerateMockeryYaml_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateMockeryYaml'
type Executor_GenerateMockeryYaml_Call struct {
	*mock.Call
}

// GenerateMockeryYaml is a helper method to define mock.On call
//   - moduleName string
//   - dir string
//   - outPath string
//   - logger *slog.Logger
func (_e *Executor_Expecter) GenerateMockeryYaml(moduleName interface{}, dir interface{}, outPath interface{}, logger interface{}) *Executor_GenerateMockeryYaml_Call {
	return &Executor_GenerateMockeryYaml_Call{Call: _e.mock.On("GenerateMockeryYaml", moduleName, dir, outPath, logger)}
}

func (_c *Executor_GenerateMockeryYaml_Call) Run(run func(moduleName string, dir string, outPath string, logger *slog.Logger)) *Executor_GenerateMockeryYaml_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *slog.Logger
		if args[3] != nil {
			arg3 = args[3].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Executor_GenerateMockeryYaml_Call) Return(err error) *Executor_GenerateMockeryYaml_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Executor_GenerateMockeryYaml_Call) RunAndReturn(run func(moduleName string, dir string, outPath string, logger *slog.Logger) error) *Executor_GenerateMockeryYaml_Call {
	_c.Call.Return(run)
	return _c
}
