---
name: taskfile-without-empty-lines
"on":
  push:
permissions:
  contents: read
jobs:
  taskfile-without-empty-lines:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - run: |
          yaml_file="Taskfile.yml"
          empty_lines=$(grep -n -e '^$' "$yaml_file")

          awk '
            BEGIN {
              in_block = 0;
              empty_line_found = 0;
              impacted_lines = "";
            }
            # Start of block patterns: "- |" and "sh: |"
            /^[[:space:]]*- *\|/ || /^[[:space:]]*sh: *\|/ {
              in_block = 1;
              next;
            }
            # Detect empty line
            /^$/ {
              if (in_block == 0) {
                empty_line_found = 1;
                impacted_lines = impacted_lines NR ", ";
              }
            }
            {
              # Exit block strategy: Detecting a YAML line that is not nested or indented
              if (in_block == 1 && !match($0, /^[[:space:]]/)) {
                in_block = 0;
              }
            }
            END {
              if (empty_line_found == 1) {
                sub(/, $/, "", impacted_lines); # Clean trailing comma
                print "Empty lines found at lines: " impacted_lines;
                exit 1;
              } else {
                print "No empty lines outside specified blocks found in $yaml_file.";
              }
            }
          ' "$yaml_file"
          exit_status=$?

          if [[ $exit_status -ne 0 ]]; then
            echo "❌ Empty lines outside of '- |' blocks, found in $yaml_file:"
            exit 1
          fi

          echo "✅ $yaml_file is without empty lines!"
